app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from courses.views import course_list
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('payments/', include('payments.urls')),
    path('', course_list, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('course_list/', course_list, name='course_list'),
    path('course_detail/<int:pk>/', course_detail, name='course_detail'),
    path('create/', course_create, name='course_create'),
    path('course_update/<int:pk>/', course_update, name='course_update'),
    path('course_delete/<int:pk>/', course_delete, name='course_delete'),
    path('part/<int:course_id>/', course_part, name='course_part'),
    path('edit_part/<int:part_id>/', edit_course_part, name='edit_course_part'),
    path('delete_part/<int:part_id>/', delete_course_part, name='delete_course_part'),
    path('comment_delete/<int:coment_id>/', comment_delete, name='comment_delete'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:id>/', profile, name='profile'),
    path('password_reset/', password_reset, name='password_reset'),
]

courses/models.py
from django.db import models
from app import settings
from users.models import CustomUser

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    def __str__(self):
        return self.name
    

class Course(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField()
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='courses')
    purchased_by = models.ManyToManyField(CustomUser, through='CoursePurchase', related_name='purchased_courses')
    payment_link = models.URLField(null=True, blank=True)
    has_purchased = models.BooleanField(default=False)
    
    stripe_product_id = models.CharField(max_length=255, null=True, blank=True)
    stripe_price_id = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return self.title
    
class CoursePart(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="parts")
    title = models.CharField(max_length=1000)
    content = models.TextField(blank=True, null=True)
    is_free = models.BooleanField(default=False)
    video = models.FileField(upload_to='course_parts/', blank=True, null=True)
    
class CoursePurchase(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=250)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.user} -> {self.course} - {self.text[:7]}...'

courses/forms.py
from django import forms
from .models import *

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'instructor', 'price', 'video', 'category', 'payment_link']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'description': forms.Textarea(attrs={'class': 'form-control form-control-sm', 'rows': 3}),
            'instructor': forms.Select(attrs={'class': 'form-control form-control-sm'}),
            'price': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'video': forms.FileInput(attrs={'class': 'form-control form-control-sm'}),
            'category': forms.Select(attrs={'class': 'form-control form-control-sm'}),
            'payment_link': forms.URLInput(attrs={'class': 'form-control form-control-sm'}),
        }
class CoursePartForm(forms.ModelForm):
    class Meta:
        model = CoursePart
        fields = ['title', 'content', 'is_free', 'video']

courses/views.py
from django.conf import settings
import stripe
from .models import Course, Category
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required


app_name = 'courses'
stripe.api_key = settings.STRIPE_SECRET_KEY

def course_list(request):
    # Получение параметров из GET-запроса
    category_id = request.GET.get('category')  # Фильтр по категории
    search_query = request.GET.get('search', '')  # Поисковый запрос
    sort_by = request.GET.get('sort')  # Сортировка

    # Начальный набор курсов
    courses = Course.objects.all()

    # Фильтр по категории
    if category_id:
        courses = courses.filter(category_id=category_id)

    # Поиск по названию
    if search_query:
        courses = courses.filter(title__icontains=search_query)

    # Сортировка курсов
    if sort_by == 'newest':
        courses = courses.order_by('-created_at')  # Сначала новые
    elif sort_by == 'price':
        courses = courses.order_by('price')  # По возрастанию це
    # Получение всех категорий для отображения в фильтрах
    categories = Category.objects.all()

    # Передача данных в шаблон
    return render(request, 'courses/course_list.html', {
        'courses': courses,  # Курсы
        'categories': categories,  # Категории для фильтрации
        'selected_category': category_id,  # Выбранная категория
        'search_query': search_query,  # Поисковый запрос
        'sort_by': sort_by,  # Текущая сортировка
    })


@login_required
def course_create(request):
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)  # Не забудьте добавить request.FILES для загрузки файлов
        if form.is_valid():
            # Сохраняем курс в базе данных
            course = form.save(commit=False)  # Не сохраняем еще в БД
            course.instructor = request.user  # Устанавливаем текущего пользователя как инструктора
            course.save()  # Теперь сохраняем курс

            # Создание продукта в Stripe
            product = stripe.Product.create(
                name=course.title,
                description=course.description,
            )

            # Создание цены в Stripe
            price = stripe.Price.create(
                unit_amount=int(course.price * 100),  # Указываем цену в центах
                currency='usd',  # Укажите нужную валюту
                product=product.id,
            )

            # Сохраняем идентификаторы Stripe в модели Course
            course.stripe_product_id = product.id
            course.stripe_price_id = price.id
            course.save()  # Сохраняем изменения в модели Course

            return redirect('courses:course_list')
    else:
        form = CourseForm()
    return render(request, 'courses/course_create.html', {'form': form})


def course_detail(request, pk):
    # Получаем курс
    course = get_object_or_404(Course, pk=pk)

    # Проверка, приобрел ли пользователь курс
    has_purchased = course.purchased_by.filter(id=request.user.id).exists()
    print(has_purchased)
    if request.method == 'POST':

        comment_text = request.POST.get('comment', '').strip()
        if comment_text:
            Comment.objects.create(
                course=course,
                user=request.user,
                text=comment_text
            )
            return redirect('courses:course_detail', pk=course.id)
        # Проверка успешной оплаты и статуса покупки
        if request.POST.get('success') == 'true' and not has_purchased:
            # Добавление пользователя в список покупателей
            course.purchased_by.add(request.user)
            course.save()

            messages.success(request, "Вы успешно приобрели курс и получили доступ ко всем его материалам!")
        else:
            messages.warning(request, "Вы уже приобрели этот курс или произошла ошибка.")

    # Отображение страницы курса
    return render(request, 'courses/course_detail.html', {
        'course': course,
        'has_purchased': has_purchased,
    })

@login_required
def course_update(request, pk):
    # Получение объекта Course по pk
    course = get_object_or_404(Course, id=pk)
    form = CourseForm(instance=course)

    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            form.save()
            return redirect('courses:course_detail', pk=course.id)

    context = {
        'form': form,
        'course': course,
    }

    return render(request, 'courses/course_update.html', context)

@login_required
def course_delete(request, pk):
    course = get_object_or_404(Course, pk=pk)

    # Разрешить удаление только владельцу курса или администратору
    if request.user == course.instructor or request.user.is_superuser:
        if request.method == 'POST':
            # Удаление курса
            course.delete()
            return redirect('courses:course_list')  # Перенаправление на список курсов
        return render(request, 'courses/course_delete.html', {'course': course})  # Отображение страницы подтверждения
    else:
        return redirect('courses:course_detail', pk=pk)  # Если нет прав на удаление, перенаправляем на детали курса

@login_required
def course_part(request, course_id):
    course = get_object_or_404(Course, id=course_id)

    if request.method == "POST":
        form = CoursePartForm(request.POST, request.FILES)
        if form.is_valid():
            part = form.save(commit=False)
            part.course = course
            part.save()
            return redirect('courses:course_detail', pk=course.id)
    else:
        form = CoursePartForm()

    return render(request, 'courses/course_part.html', {'form': form, 'course': course})

@login_required
def edit_course_part(request, part_id):
    part = get_object_or_404(CoursePart, id=part_id)

    if request.method == "POST":
        form = CoursePartForm(request.POST, request.FILES, instance=part)
        if form.is_valid():
            form.save()
            return redirect('courses:course_detail', pk=part.course.id)
    else:
        form = CoursePartForm(instance=part)

    return render(request, 'courses/course_edit_part.html', {'form': form, 'part': part})

@login_required
def delete_course_part(request, part_id):
    # Получаем объект CoursePart или возвращаем 404, если не найден
    part = get_object_or_404(CoursePart, id=part_id)
    
    # Если запрос POST, то удаляем объект
    if request.method == "POST":
        # Сохраняем course_id до удаления
        course_id = part.course.id
        part.delete()  # Удаляем раздел курса
        
        # Перенаправляем на страницу с деталями курса
        return redirect('courses:course_detail', pk=course_id)
    
    # Если запрос GET, показываем страницу подтверждения удаления
    return render(request, 'courses/course_delete_part.html', {'part': part})

def comment_delete(request, coment_id):
    coment = get_object_or_404(Comment, pk=coment_id)
    course_id = coment.course.id
    coment.delete()
    return redirect('courses:course_detail', pk=course_id)

courses/templates/courses/course_create.html
{% extends 'base.html' %}
{% load form_tags %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Создание нового курса</h2>
    <form method="post" enctype="multipart/form-data" class="mx-auto" style="max-width: 500px;">
        {% csrf_token %}
        
        <!-- Поле Название -->
        <div class="mb-3">
            <label for="{{ form.title.id_for_label }}" class="form-label">Название</label>
            {{ form.title|add_class:"form-control form-control-sm" }}
            {% if form.title.errors %}
                <div class="text-danger">{{ form.title.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Описание -->
        <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
            {{ form.description|add_class:"form-control form-control-sm" }}
            {% if form.description.errors %}
                <div class="text-danger">{{ form.description.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Инструктор -->
        <div class="mb-3">
            <label for="{{ form.instructor.id_for_label }}" class="form-label">Инструктор</label>
            {{ form.instructor|add_class:"form-control form-control-sm" }}
            {% if form.instructor.errors %}
                <div class="text-danger">{{ form.instructor.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Цена -->
        <div class="mb-3">
            <label for="{{ form.price.id_for_label }}" class="form-label">Цена</label>
            {{ form.price|add_class:"form-control form-control-sm" }}
            {% if form.price.errors %}
                <div class="text-danger">{{ form.price.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Видео -->
        <div class="mb-3">
            <label for="{{ form.video.id_for_label }}" class="form-label">Видео</label>
            {{ form.video|add_class:"form-control form-control-sm" }}
            {% if form.video.errors %}
                <div class="text-danger">{{ form.video.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Категория -->
        <div class="mb-3">
            <label for="{{ form.category.id_for_label }}" class="form-label">Категория</label>
            {{ form.category|add_class:"form-select form-select-sm" }}
            {% if form.category.errors %}
                <div class="text-danger">{{ form.category.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Поле Ссылка на оплату -->
        <div class="mb-3">
            <label for="{{ form.payment_link.id_for_label }}" class="form-label">Ссылка на оплату</label>
            {{ form.payment_link|add_class:"form-control form-control-sm" }}
            {% if form.payment_link.errors %}
                <div class="text-danger">{{ form.payment_link.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Кнопка отправки -->
        <button type="submit" class="btn btn-primary btn-sm">Создать курс</button>
    </form>
</div>
{% endblock %}

courses/templates/courses/course_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h1 class="text-danger">Подтверждение удаления</h1>
    <p>Вы уверены, что хотите удалить курс "{{ course.title }}"?</p>
    <p>Вы не сможете востанавить курса после удаления.</p>

    <!-- Форма для удаления курса -->
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Удалить курс</button>
      <a href="{% url 'courses:course_detail' course.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
  </div>
{% endblock %}

courses/templates/courses/course_delete_part.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center text-danger mb-4">Удалить часть курса</h1>
    <div class="alert alert-warning">
        <p>Вы уверены, что хотите удалить часть курса <strong>{{ part.title }}</strong>?</p>
    </div>
    <div class="d-flex justify-content-end">
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
        <a href="{% url 'courses:course_detail' part.course.id %}" class="btn btn-secondary ms-3">Отмена</a>
    </div>
</div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5">
        <!-- Блок для сообщений -->
        {% if messages %}
        <div class="alert-messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mt-3">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    <h1 class="mb-4 text-center text-primary">Детали курса</h1>
    
    <div class="card shadow-sm">
        <div class="card-body">
            <!-- Информация о курсе -->
            <div class="mb-3">
                <h5 class="font-weight-bold text-muted">Заголовок:</h5>
                <p class="form-control-plaintext">{{ course.title }}</p>
            </div>

            <h5>О преподавателе</h5>
            <p class="text-muted">{{ course.date }} - 
                {% if course.instructor %}
                    <a href="{% url 'users:profile' course.instructor.id %}">@{{ course.instructor.username }}</a>
                {% else %}
                    Автор не указан
                {% endif %}
            </p>

            <div class="mb-3">
                <h5 class="font-weight-bold text-muted">Описание:</h5>
                <p class="form-control-plaintext">{{ course.description }}</p>
            </div>

            <!-- Видео -->
            <div class="mb-3">
                <h5 class="font-weight-bold text-muted">Видео:</h5>
                {% if course.video %}
                    <video id="course-video" class="w-100 mt-2" height="auto" controls>
                        <source src="{{ course.video.url }}" type="video/mp4">
                        <source src="{{ course.video.url }}" type="video/webm">
                        <source src="{{ course.video.url }}" type="video/ogg">
                        Ваш браузер не поддерживает воспроизведение видео.
                    </video>
                {% else %}
                    <p>Видео отсутствует</p>
                {% endif %}
            </div>

            <!-- Части курса -->
            <div class="mt-4">
                <h5 class="font-weight-bold text-muted">Части курса:</h5>
                {% if course.parts.all %}
                    <ul class="list-group">
                        {% for part in course.parts.all %}
                            <li class="list-group-item">
                                <h6 class="d-flex justify-content-between align-items-center">
                                    Часть {{ forloop.counter }}: {{ part.title }}
                                    <div>
                                        <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#part-{{ part.id }}" aria-expanded="false" aria-controls="part-{{ part.id }}">
                                            Подробнее
                                        </button>
                                        <!-- Кнопки редактирования и удаления  -->
                                        {% if user == course.instructor or user.is_superuser %}
                                        <a href="{% url 'courses:edit_course_part' part.id %}" class="btn btn-sm btn btn-primary">Редактировать</a>
                                        <form action="{% url 'courses:delete_course_part' part.id %}" method="post" class="d-inline">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                                        </form>
                                        {% endif %}
                                    </div>
                                </h6>
            
                                <div class="collapse mt-2" id="part-{{ part.id }}">
                                    {% if part.is_free or has_purchased %}
                                        <!-- Доступная часть -->
                                        <p class="text-muted">{{ part.content }}</p>
                                        {% if part.video %}
                                            <video class="w-100" controls>
                                                <source src="{{ part.video.url }}" type="video/mp4">
                                                Ваш браузер не поддерживает воспроизведение видео.
                                            </video>
                                        {% endif %}
                                    {% else %}
                                        <!-- Закрытая часть курса -->
                                        <p class="text-danger">Часть доступна только после покупки курса.</p>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="text-muted">У этого курса нет частей.</p>
                {% endif %}
            </div>
            
            <div class="d-flex justify-content-start mt-3 gap-2">
                {% if user.is_authenticated %}
                    {% if user in course.purchased_by.all %}
                        <p class="text-success">Вы уже приобрели этот курс!</p>
                    {% else %}
                        {% if course.payment_link %}
                            <a href="{{ course.payment_link }}" class="btn btn-primary">Купить курс</a>
                        {% else %}
                            <p class="text-warning">Пока что купить курс нельзя</p>
                        {% endif %}
                    {% endif %}

                    {% if user == course.instructor or user.is_superuser %}
                        <a href="{% url 'courses:course_update' course.id %}" class="btn btn-primary">Редактировать курс</a>
                        <a href="{% url 'courses:course_delete' course.id %}" class="btn btn-danger">Удалить курс</a>
                        <a href="{% url 'courses:course_part' course.id %}" class="btn btn-success">Добавить другие части курса</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary">
                        Войдите, чтобы купить курс
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Комментарии  -->
    <div class="row mt-4">
        <div class="col-8">
            <h3>Комментарии к курсу: {{ course.title }}</h3>
            <hr>
            <form action="" method="post" class="d-flex">
                {% csrf_token %}
                <input type="text" name="comment" class="form-control" placeholder="Введите комментарий...">
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>

            <div class="d-flex flex-column gap-2 mt-3">
                {% for comment in course.comment_set.all %}
                    <div class="d-flex align-items-center gap-2 justify-content-between">
                        <div class="d-flex align-items-center gap-2">
                            <div class="d-flex flex-column gap-1">
                                <span>
                                    <strong>{{ comment.user.username }}</strong>
                                    <sup>{{ comment.date|date:"d M Y H:i" }}</sup>
                                </span>
                                <p>{{ comment.text }}</p>
                            </div>
                        </div>
                        {% if request.user == comment.user or request.user.is_superuser %}
                            <a href="{% url 'courses:comment_delete' comment.id %}" class="btn btn-danger">
                                <i class='bx bx-trash'></i> Удалить
                            </a>
                        {% endif %}
                    </div>
                {% empty %}
                    <p>Комментариев пока нет.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script>
    // Скрипт для скрытия уведомлений через несколько секунд
    document.addEventListener('DOMContentLoaded', function() {
        // Находим все сообщения
        const messages = document.querySelectorAll('.alert');
        
        // Проходим по каждому сообщению
        messages.forEach(function(message) {
            // Через 3 секунды скрываем сообщение
            setTimeout(function() {
                message.style.display = 'none';
            }, 3000); // 3000 миллисекунд = 3 секунды
        });
    });
</script>
{% endblock %}

courses/templates/courses/course_edit_part.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center text-primary mb-4">Редактировать часть курса</h1>
    <div class="card shadow-sm p-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="form-label">Название</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_content" class="form-label">Содержание</label>
                {{ form.content }}
            </div>
            <div class="mb-3">
                <label for="id_is_free" class="form-label">Бесплатный</label>
                {{ form.is_free }}
            </div>
            <div class="mb-3">
                <label for="id_video" class="form-label">Видео</label>
                {{ form.video }}
            </div>
            <div class="d-flex justify-content-end mt-3">
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                <a href="{% url 'courses:course_detail' part.course.id %}" class="btn btn-secondary ms-3">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

courses/templates/courses/course_list.html
<!-- course_list.html -->
{% extends 'base.html' %}

{% block title %}Курсы{% endblock %}

{% block content %}

<!-- Форма фильтрации -->
<form method="get" class="
filter-form row align-items-center">
  <!-- Категории -->
  <div class="col-md-4">
      <select name="category" id="category" class="form-select">
          <option value="">Все категории</option>
          {% for category in categories %}
              <option value="{{ category.id }}" {% if category_id == category.id|stringformat:"s" %}selected{% endif %}>
                  {{ category.name }}
              </option>
          {% endfor %}
      </select>
  </div>

  <!-- Поле поиска -->
  <div class="col-md-4">
      <input type="text" name="search" id="search" class="form-control" value="{{ search_query }}" placeholder="Введите название курса">
  </div>

  <!-- Кнопка -->
  <div class="col-md-2">
      <button type="submit" class="btn btn-primary w-100">Применить</button>
  </div>
</form>



<div class="container mt-5">
  <h1>Список курсов</h1>

  <!-- Кнопка для создания курса доступна только для преподавателя и администратора -->
  {% if request.user.role == 'teacher' or request.user.role == 'admin' %}
    <a href="{% url 'courses:course_create' %}" class="btn btn-primary mb-2">Создать курс</a>
  {% endif %}
  
  {% if request.user.is_superuser %}
    <a href="{% url 'admin:index' %}" class="btn btn-primary mb-2">Страница админа</a>
  {% endif %}

  <div class="row">
    {% for course in courses %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ course.title }}</h5>
          <p class="card-text">{{ course.description|truncatechars:100 }}</p>
          <a href="{% url 'courses:course_detail' course.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

courses/templates/courses/course_update.html
{% extends 'base.html' %}
{% load form_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <h2 class="mb-4 text-center text-primary">Обновить курс: {{ course.title }}</h2>
            <form method="post" enctype="multipart/form-data" class="bg-light p-4 rounded shadow">
                {% csrf_token %}
                <!-- Заголовок -->
                <div class="mb-3">
                    <label for="id_title" class="form-label">Заголовок</label>
                    {{ form.title|add_class:"form-control" }}
                </div>
                
                <!-- Описание -->
                <div class="mb-3">
                    <label for="id_description" class="form-label">Описание</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                
                <!-- Инструктор -->
                <div class="mb-3">
                    <label for="id_instructor" class="form-label">Инструктор</label>
                    {{ form.instructor|add_class:"form-control" }}
                </div>
                
                <!-- Цена -->
                <div class="mb-3">
                    <label for="id_price" class="form-label">Цена</label>
                    {{ form.price|add_class:"form-control" }}
                </div>
                
                <!-- Видео -->
                <div class="mb-3">
                    <label for="id_video" class="form-label">Видео</label>
                    {{ form.video|add_class:"form-control" }}
                </div>

                <div class="mb-3">
                    <label for="{{ form.category.id_for_label }}" class="form-label">Категория</label>
                    {{ form.category|add_class:"form-select form-select-sm" }}
                    {% if form.category.errors %}
                        <div class="text-danger">{{ form.category.errors }}</div>
                    {% endif %}
                </div>

                        <!-- Поле Ссылка на оплату -->
                <div class="mb-3">
                    <label for="{{ form.payment_link.id_for_label }}" class="form-label">Ссылка на оплату</label>
                    {{ form.payment_link|add_class:"form-control form-control-sm" }}
                    {% if form.payment_link.errors %}
                        <div class="text-danger">{{ form.payment_link.errors }}</div>
                    {% endif %}
                </div>
                
                <!-- Кнопки -->
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a href="{% url 'courses:course_detail' course.id %}" class="btn btn-secondary">Отмена</a>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}